name: Create Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Create Serveless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Lambda Function
        run: |
          aws cloudformation create-stack --stack-name my-infra-stack --template-body file://infra.yaml --capabilities CAPABILITY_IAM
